"""Derive the Windows validation workflow FROM the release workflow. Never write a second recipe.

WHY
---
Every failure in the ablation ladder came from me re-typing something the working workflow already had:
a path, a working-directory, an abbreviated SHA, a set of CMake flags, a parameter name that did not
exist. Six runs, all of them the same mistake wearing different clothes -- I wrote from memory instead of
reading the file that works.

So the validation does not get its own recipe. It gets build-windows.yml's build steps, copied byte for
byte, with validation steps appended. --check re-derives and diffs, so the two cannot drift: if someone
edits the release workflow, this fails until the validation is regenerated from it.

The one thing deliberately NOT copied is everything after the build: publishing, signing, release
upload. The validation must be incapable of publishing, not merely instructed not to.

    python derive_validation_workflow.py           write it
    python derive_validation_workflow.py --check   fail if it drifted from build-windows.yml
    python derive_validation_workflow.py --self-test
"""
import argparse
import difflib
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
FUENTE = REPO / ".github/workflows/build-windows.yml"
DESTINO = REPO / ".github/workflows/validate-windows-fix.yml"

# Copy up to and including the app build. Everything past it publishes.
ULTIMO_PASO_COPIADO = "npm run tauri build"

CABECERA = """# GENERATED by tools/ci/derive_validation_workflow.py -- DO NOT EDIT BY HAND.
#
# The build steps below are copied byte for byte from build-windows.yml, the workflow that actually
# produces the shipped installer. They are not a second recipe: every ablation failure came from me
# re-typing something the working workflow already had -- a path, a working-directory, an abbreviated
# SHA, CMake flags, a parameter that did not exist. `derive_validation_workflow.py --check` re-derives
# and diffs, so the two cannot drift.
#
# Everything after the app build -- signing, release upload, latest.json -- is deliberately absent. This
# must be incapable of publishing, not merely instructed not to.
#
# What it proves, on the real commit, with real sidecars:
#   the test executable LOADS       exit=0 / 0x00000000
#   it lists at least 61 tests      58 was rc5; 61 is rc5 plus the shutdown tests that now run
#   TaskDialogIndirect is absent    the fail-closed gate, not a grep
#   comctl32.dll is absent
#   every Rust and JavaScript test passes

name: Validate the Windows fix (no publishing)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit to validate (a full SHA, never abbreviated -- checkout asks the remote for a ref)
        required: true

permissions:
  contents: read

jobs:
  validate:
    runs-on: windows-2022
    steps:
"""

VALIDACION = '''
      # ---------------------------------------------------------------------------------------------
      # From here down: validation. Nothing above this line was written by hand.
      # ---------------------------------------------------------------------------------------------

      - name: The test executable loads, and lists its tests
        id: load
        shell: pwsh
        run: |
          $env:RANDOMX_LIB_DIR = (Split-Path $env:RANDOMX_LIB)
          New-Item -ItemType Directory -Force -Path C:\\evidence | Out-Null
          . "$env:GITHUB_WORKSPACE\\tools\\ci\\Invoke-NativeProcess.ps1"

          $json = cargo test --manifest-path src-tauri/Cargo.toml --features mainnet --lib --no-run --message-format=json
          $json | Out-File C:\\evidence\\cargo-json.txt

          # profile.test marks THIS artifact as a test binary. target.test only says a target CAN be
          # tested -- filtering on that matched nothing and cost a whole run.
          $found = @()
          foreach ($line in $json) {
            if ($line -notmatch '^\\s*\\{') { continue }
            try { $m = $line | ConvertFrom-Json } catch { continue }
            if ($m.reason -eq 'compiler-artifact' -and $m.executable -and $m.profile.test -eq $true) {
              $found += $m.executable
            }
          }
          if ($found.Count -ne 1) { throw "expected exactly 1 test executable, found $($found.Count)" }
          $exe = $found[0]
          Copy-Item $exe C:\\evidence\\test.exe
          $sha = (Get-FileHash $exe -Algorithm SHA256).Hash

          # --list needs it to LOAD but runs no test. The exit code comes off the process object;
          # nothing critical is read through a pipeline.
          $r = Invoke-NativeProcess -FilePath $exe -Arguments @('--list') -OutputDir C:\\evidence
          Write-NativeProcessReport -Result $r -PreviewLines 5
          $tests = ($r.StdOut -split "`n" | Where-Object { $_ -match ': test$' }).Count

          Write-Host "SHA=${{ inputs.ref }} EXE_SHA256=$sha EXIT=$($r.ExitCode) HEX=$($r.ExitCodeHex) TESTS=$tests"
          "exe_sha256=$sha"          | Out-File -Append $env:GITHUB_OUTPUT
          "exit_dec=$($r.ExitCode)"  | Out-File -Append $env:GITHUB_OUTPUT
          "tests=$tests"             | Out-File -Append $env:GITHUB_OUTPUT

          if ($r.ExitCode -ne 0) {
            throw "the test executable does not load: exit $($r.ExitCode) / $($r.ExitCodeHex). rc6 died here with 0xC0000139."
          }
          if ($tests -lt 61) {
            throw "listed $tests tests, expected at least 61. rc5 had 58; 61 is rc5 plus the shutdown tests. Fewer means they were deleted, not fixed."
          }

      - name: It must never import TaskDialogIndirect again
        shell: pwsh
        run: |
          python tools/ci/check_test_exe_imports.py --self-test
          if ($LASTEXITCODE -ne 0) { throw "the import gate does not trust itself" }
          dumpbin /IMPORTS C:\\evidence\\test.exe | Out-File C:\\evidence\\imports.txt
          python tools/ci/check_test_exe_imports.py C:\\evidence\\test.exe
          if ($LASTEXITCODE -ne 0) { throw "the test executable imports something that kills it before main" }

      - name: Every Rust test
        shell: pwsh
        run: |
          $env:RANDOMX_LIB_DIR = (Split-Path $env:RANDOMX_LIB)
          cargo test --manifest-path src-tauri/Cargo.toml --features mainnet --lib -- --nocapture 2>&1 | Tee-Object C:\\evidence\\rust-tests.txt
          if ($LASTEXITCODE -ne 0) { throw "Rust tests failed" }

      - name: Every JavaScript test
        shell: pwsh
        run: |
          npm test 2>&1 | Tee-Object C:\\evidence\\js-tests.txt
          if ($LASTEXITCODE -ne 0) { throw "JavaScript tests failed" }

      - name: Seal the evidence
        if: always()
        shell: pwsh
        run: |
          $m = [ordered]@{
            run_id          = "${{ github.run_id }}"
            run_attempt     = "${{ github.run_attempt }}"
            workflow_commit = "${{ github.sha }}"
            validated_ref   = "${{ inputs.ref }}"
            validated_sha   = "$(git rev-parse HEAD)"
            runner          = "windows-2022"
            generated_utc   = [DateTime]::UtcNow.ToString('o')
            test_exe_sha256 = "${{ steps.load.outputs.exe_sha256 }}"
            exit_decimal    = "${{ steps.load.outputs.exit_dec }}"
            tests_listed    = "${{ steps.load.outputs.tests }}"
            tool_hashes     = @{}
          }
          Get-ChildItem tools/ci -Filter *.ps1 | ForEach-Object {
            $m.tool_hashes[$_.Name] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash
          }
          # No -Encoding UTF8: PS 5.1 writes a BOM there and json.load, jq and fromJSON all choke.
          $m | ConvertTo-Json -Depth 4 | Out-File C:\\evidence\\manifest.json
          Get-Content C:\\evidence\\manifest.json

      - name: Keep the installer and the evidence, published nowhere
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}-attempt-${{ github.run_attempt }}-windows-validation
          path: |
            C:\\evidence\\*
            src-tauri/target/release/bundle/nsis/*.exe
          if-no-files-found: warn
'''


def pasos_de_build(texto):
    """The build steps from build-windows.yml, verbatim, up to and including the app build."""
    i = texto.find("    steps:")
    if i < 0:
        raise SystemExit("build-windows.yml has no steps:")
    corte = texto.find(ULTIMO_PASO_COPIADO, i)
    if corte < 0:
        raise SystemExit(f"could not find '{ULTIMO_PASO_COPIADO}' -- the release workflow changed shape")
    fin = texto.find("\n      - name:", corte)
    if fin < 0:
        fin = len(texto)
    bloque = texto[i + len("    steps:"):fin]

    # The ref comes from the input: this validates one commit, named explicitly and never abbreviated.
    bloque = re.sub(r"(uses: actions/checkout@v4\n)(?!(\s+with:))",
                    r"\1        with:\n          ref: ${{ inputs.ref }}\n", bloque, count=1)

    # DELIBERATE, DECLARED difference from the release workflow -- not drift. The approval conditions
    # require validation to be incapable of signing, so the production key is not passed. With the key
    # gone, createUpdaterArtifacts must also be forced off: left on, tauri would try to sign an artifact
    # it cannot and fail. A precondition refuses to run if a key reaches this job anyway; a postcondition
    # fails if any .sig is produced. The NSIS installer -- the thing under test -- is still built.
    paso_firmado = re.compile(
        r"      - name: Build the Tauri app[^\n]*\n"
        r"        run: npm run tauri build[^\n]*\n"
        r"        env:\n"
        r"          TAURI_SIGNING_PRIVATE_KEY:[^\n]*\n"
        r"          TAURI_SIGNING_PRIVATE_KEY_PASSWORD:[^\n]*\n")
    paso_validacion = (
        "      - name: Build the Tauri app (NSIS installer, no signing, no updater artifacts)\n"
        "        shell: pwsh\n"
        "        run: |\n"
        "          if ($env:TAURI_SIGNING_PRIVATE_KEY) { throw \"the validation job must not receive the production signing key\" }\n"
        "          npm run tauri build -- --features mainnet --config src-tauri/tauri.validation.conf.json\n"
        "          $sigs = Get-ChildItem -Recurse -Filter *.sig -ErrorAction SilentlyContinue\n"
        "          if ($sigs) { throw \"a .sig artifact was produced: validation must not sign -- $($sigs.FullName -join ', ')\" }\n")
    bloque, n = paso_firmado.subn(paso_validacion, bloque)
    if n != 1:
        raise SystemExit(
            f"expected exactly 1 signed tauri-build step to strip, found {n}. build-windows.yml changed "
            f"shape around signing; update the transform before deriving.")

    return bloque.rstrip("\n")


def generar():
    return CABECERA + pasos_de_build(FUENTE.read_text(encoding="utf-8")) + "\n" + VALIDACION


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()

    if a.self_test:
        t = FUENTE.read_text(encoding="utf-8")
        fallos = 0
        b = pasos_de_build(t)
        for necesario in ("randomx", "vcpkg", "bitcoind", "dtolnay/rust-toolchain"):
            if necesario not in b.lower():
                print(f"  FAIL  the copied block has no {necesario}: it would not build")
                fallos += 1
            else:
                print(f"  PASS  copies-{necesario}")
        for prohibido in ("softprops/action-gh-release", "latest.json", "minisign"):
            if prohibido in b:
                print(f"  FAIL  the copied block contains {prohibido}: it could publish")
                fallos += 1
        print("  PASS  copies-nothing-that-publishes")

        # The signing key must be stripped, and the validation config must be passed. This is the
        # declared difference, so it must actually hold in the output.
        if "TAURI_SIGNING_PRIVATE_KEY:" in b:
            print("  FAIL  the signing key survived into the validation build step")
            fallos += 1
        else:
            print("  PASS  strips-the-signing-key")
        if "tauri.validation.conf.json" not in b:
            print("  FAIL  createUpdaterArtifacts is not forced off; a keyless build would fail trying to sign")
            fallos += 1
        else:
            print("  PASS  forces-createUpdaterArtifacts-off")

        if "\t" in generar():
            print("  FAIL  the generated file has a tab -- a path that escaped twice")
            fallos += 1
        else:
            print("  PASS  no-tabs")
        print()
        print("SELF-TEST FAILED" if fallos else "self-test OK: the derived block builds and cannot publish")
        return 1 if fallos else 0

    nuevo = generar()
    if a.check:
        if not DESTINO.exists():
            print(f"FAIL: {DESTINO.name} does not exist. Run without --check.")
            return 1
        viejo = DESTINO.read_text(encoding="utf-8")
        if viejo != nuevo:
            print(f"FAIL: {DESTINO.name} has drifted from build-windows.yml.")
            print("Two recipes for one build is how the ladder failed six times. Regenerate it.\n")
            for l in list(difflib.unified_diff(viejo.splitlines(), nuevo.splitlines(),
                                               "committed", "derived", lineterm=""))[:25]:
                print(f"  {l}")
            return 1
        print(f"OK: {DESTINO.name} matches build-windows.yml.")
        return 0

    DESTINO.write_text(nuevo, encoding="utf-8", newline="\n")
    print(f"written: {DESTINO.relative_to(REPO)}")
    print(f"  {len(nuevo.splitlines())} lines, build steps copied from build-windows.yml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
