"""Derive the seven-scenario installer-hook workflow. Reuse the release recipe's build; never re-type it.

WHY DERIVED
-----------
Same lesson as the validation workflow: every ablation failure was me re-typing a path, a flag, a
working-directory the working workflow already had. So the build half here is copied byte for byte from
build-windows.yml, up to and including the bitcoind build -- that is all the scenarios need to spawn real
nodes. --check re-derives and diffs so the two cannot drift.

PHASE 1 ONLY
------------
This runs the shipped shutdown-brisvia-node.ps1 directly against real bitcoind nodes -- the fast, precise
half ChatGPT recommended first. The full installer /S pass is a later phase and needs the NSIS installer,
which the validation workflow builds. Kept separate so a bug in one does not mask the other.

    python derive_scenario_workflow.py           write it
    python derive_scenario_workflow.py --check   fail if it drifted from build-windows.yml
    python derive_scenario_workflow.py --self-test
"""
import argparse
import difflib
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
FUENTE = REPO / ".github/workflows/build-windows.yml"
DESTINO = REPO / ".github/workflows/test-installer-scenarios.yml"

# Copy the build up to and including bitcoind. The scenarios need bitcoind.exe and nothing past it.
ULTIMO_PASO_COPIADO = "Configure and build bitcoind + bitcoin-cli"

SCENARIOS = [
    "solo-brisvia", "brisvia-plus-foreign", "foreign-only", "unicode-datadir",
    "stale-reused-pid", "bad-rpc-channel", "multiple-ambiguous",
]

CABECERA = """# GENERATED by tools/ci/derive_scenario_workflow.py -- DO NOT EDIT BY HAND.
#
# Phase 1 of the installer-hook validation: run the shipped shutdown-brisvia-node.ps1 directly against
# real bitcoind nodes, one clean job per scenario. The build half (checkout, RandomX, bitcoind) is copied
# byte for byte from build-windows.yml; `derive_scenario_workflow.py --check` re-derives and diffs so the
# two cannot drift. The full installer /S pass is a separate later phase.
#
# The nodes are launched the way the app launches them -- `bitcoind -datadir=<dd>` on the command line,
# chain and rpcport in bitcoin.conf -- so the scenarios exercise the real identification path, including
# the chain-from-conf fallback, instead of a convenient shortcut that would pass while the installer fails.

name: Installer shutdown scenarios (phase 1, direct)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit to test (full SHA, never abbreviated)
        required: true

permissions:
  contents: read

jobs:
  build-node:
    runs-on: windows-2022
    steps:
"""

SUBIR_NODE = '''
      - name: Stage bitcoind for the scenario jobs
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path C:\\node | Out-Null
          $bd = Get-ChildItem build -Recurse -Filter bitcoind.exe | Select-Object -First 1
          if (-not $bd) { throw "no bitcoind.exe was built" }
          Copy-Item $bd.FullName C:\\node\\bitcoind.exe
          "bitcoind sha256 $((Get-FileHash C:\\node\\bitcoind.exe -Algorithm SHA256).Hash)" | Write-Host

      - name: Upload bitcoind
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}-attempt-${{ github.run_attempt }}-bitcoind
          path: C:\\node\\bitcoind.exe
          if-no-files-found: error
'''

SCENARIOS_JOB = """
  scenarios:
    needs: build-node
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        scenario: [__SCENARIOS__]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Get the built bitcoind
        uses: actions/download-artifact@v4
        with:
          name: run-${{ github.run_id }}-attempt-${{ github.run_attempt }}-bitcoind
          path: node

      - name: Run scenario ${{ matrix.scenario }}
        shell: pwsh
        run: |
          $work = Join-Path $env:RUNNER_TEMP "scn-${{ matrix.scenario }}"
          New-Item -ItemType Directory -Force -Path $work | Out-Null
          & tools\\ci\\run-shutdown-scenario.ps1 `
              -Scenario ${{ matrix.scenario }} `
              -BitcoindExe (Resolve-Path node/bitcoind.exe) `
              -ShutdownScript (Resolve-Path src-tauri/windows/shutdown-brisvia-node.ps1) `
              -WorkRoot $work
          $code = $LASTEXITCODE
          Copy-Item (Join-Path $work 'evidence.jsonl') "C:\\evidence-${{ matrix.scenario }}.jsonl" -ErrorAction SilentlyContinue
          if ($code -ne 0) { throw "scenario ${{ matrix.scenario }} failed (exit $code)" }

      - name: Keep the evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-${{ github.run_id }}-attempt-${{ github.run_attempt }}-scenario-${{ matrix.scenario }}
          path: C:\\evidence-${{ matrix.scenario }}.jsonl
          if-no-files-found: warn
"""


def pasos_hasta_bitcoind(texto):
    i = texto.find("    steps:")
    if i < 0:
        raise SystemExit("build-windows.yml has no steps:")
    corte = texto.find(ULTIMO_PASO_COPIADO, i)
    if corte < 0:
        raise SystemExit(f"could not find '{ULTIMO_PASO_COPIADO}' -- build-windows.yml changed shape")
    fin = texto.find("\n      - name:", corte)
    if fin < 0:
        fin = len(texto)
    bloque = texto[i + len("    steps:"):fin]
    # This validates one commit, named explicitly. Add the ref to the first checkout only.
    import re
    bloque = re.sub(r"(uses: actions/checkout@v4\n)(?!(\s+with:))",
                    r"\1        with:\n          ref: ${{ inputs.ref }}\n", bloque, count=1)
    return bloque.rstrip("\n")


def generar():
    build = pasos_hasta_bitcoind(FUENTE.read_text(encoding="utf-8"))
    scn = SCENARIOS_JOB.replace("__SCENARIOS__", ", ".join(SCENARIOS))
    return CABECERA + build + "\n" + SUBIR_NODE + scn


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()

    if a.self_test:
        t = FUENTE.read_text(encoding="utf-8")
        b = pasos_hasta_bitcoind(t)
        fallos = 0
        for necesario in ("randomx", "bitcoind", "vcpkg"):
            if necesario not in b.lower():
                print(f"  FAIL  the copied build has no {necesario}")
                fallos += 1
            else:
                print(f"  PASS  copies-{necesario}")
        if "tauri build" in b or "TAURI_SIGNING" in b:
            print("  FAIL  copied too far -- it reached the app build or signing")
            fallos += 1
        else:
            print("  PASS  stops-at-bitcoind-no-signing")
        out = generar()
        if "\t" in out:
            print("  FAIL  generated file has a tab")
            fallos += 1
        else:
            print("  PASS  no-tabs")
        if all(s in out for s in SCENARIOS):
            print(f"  PASS  all-{len(SCENARIOS)}-scenarios-present")
        else:
            print("  FAIL  a scenario is missing from the matrix")
            fallos += 1
        print()
        print("SELF-TEST FAILED" if fallos else "self-test OK: build copied to bitcoind, all scenarios present")
        return 1 if fallos else 0

    nuevo = generar()
    if a.check:
        if not DESTINO.exists():
            print(f"FAIL: {DESTINO.name} does not exist. Run without --check.")
            return 1
        viejo = DESTINO.read_text(encoding="utf-8")
        if viejo != nuevo:
            print(f"FAIL: {DESTINO.name} drifted from build-windows.yml. Regenerate it.\n")
            for l in list(difflib.unified_diff(viejo.splitlines(), nuevo.splitlines(),
                                               "committed", "derived", lineterm=""))[:20]:
                print(f"  {l}")
            return 1
        print(f"OK: {DESTINO.name} matches build-windows.yml.")
        return 0

    DESTINO.write_text(nuevo, encoding="utf-8", newline="\n")
    print(f"written: {DESTINO.relative_to(REPO)}")
    print(f"  {len(nuevo.splitlines())} lines, build copied to bitcoind, {len(SCENARIOS)} scenarios")
    return 0


if __name__ == "__main__":
    sys.exit(main())
