// Brisvia app UI (wallet + mining + settings). Talks to the backend only through window.brisvia.
// Every visible text comes from the i18n system (window.I18N + data-i18n in the HTML).
const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));
const T = (k, v) => window.I18N.t(k, v);
// Maps backend error codes ("ERR:CODE") to the active language; unknown ones pass through unchanged.
function transError(err) {
  if (typeof err === 'string' && err.startsWith('ERR:')) {
    const map = {
      INSUFFICIENT_FUNDS: 'errors.insufficient_funds', INVALID_ADDRESS: 'errors.invalid_address',
      FEE_TOO_LOW: 'errors.fee_too_low', NODE_STARTING: 'errors.node_starting', NODE_UNAVAILABLE: 'errors.node_unavailable',
    };
    const key = map[err.slice(4)];
    if (key) return T(key);
  }
  return err || T('errors.generic');
}

// ===================== View navigation =====================
function showView(name) {
  $$('.view').forEach((v) => (v.hidden = v.dataset.view !== name));
  $$('.nav-btn').forEach((b) => b.classList.toggle('active', b.dataset.view === name));
  if (name === 'wallet') loadWallet();
  if (name === 'settings') loadSettings();
}
$$('.nav-btn').forEach((b) => b.addEventListener('click', () => showView(b.dataset.view)));

// ===================== Primer arranque (onboarding + billetera + semilla) =====================
const ONB = ['welcome1', 'welcome2', 'welcome3'];
let onbStep = 0;
function setupStep(name) { $$('#setup .step').forEach((s) => (s.hidden = s.dataset.step !== name)); }
function renderOnb() {
  $('#onb-title').textContent = T('onboarding.' + ONB[onbStep] + '_t');
  $('#onb-text').textContent = T('onboarding.' + ONB[onbStep] + '_x');
  $$('.onb-dots .dot').forEach((d, i) => d.classList.toggle('on', i === onbStep));
  $('#onb-next').textContent = onbStep === ONB.length - 1 ? T('onboarding.start') : T('onboarding.next');
}
$('#onb-next').addEventListener('click', () => {
  if (onbStep < ONB.length - 1) { onbStep++; renderOnb(); }
  else setupStep('choose');
});

// -- Crear billetera (genera las 12 palabras reales en el backend) --
let currentSeed = [];
$('#btn-create').addEventListener('click', async () => {
  const btn = $('#btn-create'); btn.disabled = true; btn.textContent = T('onboarding.creating');
  const r = await window.brisvia.wallet.create();
  btn.disabled = false; btn.textContent = T('onboarding.create');
  if (r && r.words && r.words.length === 12) { currentSeed = r.words; showSeedStep(); }
  else { alertInline(T('onboarding.create_err')); }
});
$('#btn-import').addEventListener('click', () => { buildImportGrid(); setupStep('import'); });
function alertInline(msg) { const t = $('#onb-text'); if (t) t.textContent = msg; }

// 12 casilleros para importar la frase (uno por palabra). Pegar las 12 juntas en el primero las distribuye.
function buildImportGrid() {
  const grid = $('#import-grid');
  grid.innerHTML = '';
  for (let i = 0; i < 12; i++) {
    const li = document.createElement('li');
    const inp = document.createElement('input');
    inp.type = 'text'; inp.autocomplete = 'off'; inp.spellcheck = false; inp.setAttribute('aria-label', `${i + 1}`);
    inp.addEventListener('paste', (e) => {
      const txt = (e.clipboardData || window.clipboardData).getData('text');
      const words = txt.trim().toLowerCase().split(/\s+/).filter(Boolean);
      if (words.length > 1) {
        e.preventDefault();
        const inputs = grid.querySelectorAll('input');
        words.slice(0, 12).forEach((w, k) => { if (inputs[k]) inputs[k].value = w; });
        const next = grid.querySelectorAll('input')[Math.min(words.length, 11)];
        if (next) next.focus();
      }
    });
    inp.addEventListener('keydown', (e) => {
      if ((e.key === ' ' || e.key === 'Enter') && inp.value.trim()) {
        e.preventDefault();
        const inputs = [...grid.querySelectorAll('input')];
        const idx = inputs.indexOf(inp);
        if (inputs[idx + 1]) inputs[idx + 1].focus();
      }
    });
    li.appendChild(inp);
    grid.appendChild(li);
  }
}

// -- Show the seed (the 12 words already generated by the backend) --
function showSeedStep() {
  const grid = $('#seed-grid');
  grid.innerHTML = '';
  currentSeed.forEach((w) => { const li = document.createElement('li'); li.textContent = w; grid.appendChild(li); });
  $('#seed-ack').checked = false;
  $('#seed-next').disabled = true;
  setupStep('seed');
}
$('#seed-ack').addEventListener('change', (e) => { $('#seed-next').disabled = !e.target.checked; });
$('#seed-next').addEventListener('click', () => buildVerify());

// -- Backup verification --
let verifyPositions = [], verifyExpected = [], verifyFilled = [];
function shuffle(a) { const r = a.slice(); for (let i = r.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [r[i], r[j]] = [r[j], r[i]]; } return r; }
function buildVerify() {
  verifyPositions = shuffle(currentSeed.map((_, i) => i)).slice(0, 3).sort((a, b) => a - b);
  verifyExpected = verifyPositions.map((i) => currentSeed[i]);
  verifyFilled = [];
  const distractors = shuffle(currentSeed.filter((_, i) => !verifyPositions.includes(i))).slice(0, 3);
  const bank = shuffle([...verifyExpected, ...distractors]);
  renderVerify(bank);
  $('#verify-msg').hidden = true;
  setupStep('verify');
}
function renderVerify(bank) {
  const slots = $('#verify-slots'); slots.innerHTML = '';
  verifyPositions.forEach((pos, idx) => {
    const d = document.createElement('div');
    d.className = 'slot' + (verifyFilled[idx] ? ' filled' : '');
    d.innerHTML = `<span class="slot-n">${pos + 1}</span> <span>${verifyFilled[idx] || '—'}</span>`;
    slots.appendChild(d);
  });
  if (bank) {
    const bk = $('#verify-bank'); bk.innerHTML = '';
    bank.forEach((w) => {
      const c = document.createElement('button');
      c.className = 'chip'; c.textContent = w;
      c.addEventListener('click', () => pickWord(w, c));
      bk.appendChild(c);
    });
  }
}
function pickWord(word, chip) {
  if (verifyFilled.length >= verifyPositions.length) return;
  verifyFilled.push(word);
  chip.classList.add('used');
  renderVerify(null);
  if (verifyFilled.length === verifyPositions.length) checkVerify();
}
async function checkVerify() {
  const ok = verifyFilled.every((w, i) => w === verifyExpected[i]);
  const msg = $('#verify-msg');
  msg.hidden = false;
  $$('#verify-slots .slot').forEach((s, i) => s.classList.add(verifyFilled[i] === verifyExpected[i] ? 'ok' : 'err'));
  if (ok) {
    msg.textContent = T('onboarding.verify_ok');
    msg.className = 'verify-msg ok';
    if (window.brisvia.wallet.verifyBackup) await window.brisvia.wallet.verifyBackup(currentSeed);
    else await window.brisvia.wallet.confirmBackup();
    localStorage.setItem('brisvia_onboarded', '1');
    setTimeout(finishSetup, 900);
  } else {
    msg.textContent = T('onboarding.verify_err');
    msg.className = 'verify-msg err';
  }
}
$('#verify-reset').addEventListener('click', buildVerify);
$('#verify-back').addEventListener('click', showSeedStep);

// -- Importar --
$('#import-back').addEventListener('click', () => setupStep('choose'));
$('#import-ok').addEventListener('click', async () => {
  const words = [...$('#import-grid').querySelectorAll('input')].map((i) => i.value.trim().toLowerCase()).filter(Boolean);
  const msg = $('#import-msg');
  if (words.length !== 12) {
    msg.hidden = false; msg.className = 'verify-msg err';
    msg.textContent = T('onboarding.import_len_err', { n: words.length });
    return;
  }
  const btn = $('#import-ok'); btn.disabled = true; btn.textContent = T('onboarding.restoring');
  const r = await window.brisvia.wallet.restore(words.join(' '));
  btn.disabled = false; btn.textContent = T('onboarding.do_import');
  if (r && r.ok) {
    localStorage.setItem('brisvia_onboarded', '1');
    finishSetup();
  } else {
    msg.hidden = false; msg.className = 'verify-msg err';
    msg.textContent = r && r.error ? transError(r.error) : T('onboarding.import_err');
  }
});

function finishSetup() { $('#setup').hidden = true; showView('wallet'); if (window.brisvia.isReal) loadWallet(); }

// ===================== Minado =====================
let mining = false;
// Formats a hashrate (H/s) with the right unit, and a duration (seconds) in a human, non-technical way.
function fmtHashrate(hs) {
  hs = hs || 0;
  if (hs >= 1e9) return `${(hs / 1e9).toFixed(2)} <span class="unit">GH/s</span>`;
  if (hs >= 1e6) return `${(hs / 1e6).toFixed(2)} <span class="unit">MH/s</span>`;
  if (hs >= 1000) return `${(hs / 1000).toFixed(2)} <span class="unit">kH/s</span>`;
  return `${Math.round(hs)} <span class="unit">H/s</span>`;
}
function fmtDuration(secs) {
  secs = Math.floor(secs || 0);
  const h = Math.floor(secs / 3600), m = Math.floor((secs % 3600) / 60), s = secs % 60;
  if (h > 0) return `${h} <span class="unit">${T('mine.unit_h')}</span> ${m} <span class="unit">${T('mine.unit_min')}</span>`;
  if (m > 0) return `${m} <span class="unit">${T('mine.unit_min')}</span> ${s} <span class="unit">${T('mine.unit_s')}</span>`;
  return `${s} <span class="unit">${T('mine.unit_s')}</span>`;
}
async function refreshMine() {
  const s = await window.brisvia.getStatus();
  mining = s.mining;
  // Suppress the "Preparing…" flash for a few seconds after a live power change (the engine relaunches behind the scenes).
  const preparing = mining && s.preparing && Date.now() > suppressPreparingUntil;
  const toggle = $('#toggle');
  // While the node catches up with the network (and is not already mining), mining is not allowed yet.
  if (syncing && !mining) {
    $('#state-badge').textContent = T('net.syncing');
    $('#state-badge').className = 'badge prep';
    $('#hero-title').textContent = T('sync.title');
    $('#hero-sub').textContent = syncProgress > 0 ? T('sync.sub') + ' — ' + T('sync.progress', { p: Math.floor(syncProgress * 100) }) : T('sync.sub');
    toggle.textContent = T('mine.start');
    toggle.className = 'btn giant primary';
    toggle.disabled = true;
    return;
  }
  toggle.disabled = false;
  // Tres estados: detenido / preparando (armando el dataset, unos segundos) / participando.
  if (preparing) {
    $('#state-badge').textContent = T('mine.preparing');
    $('#state-badge').className = 'badge prep';
    $('#hero-title').textContent = T('mine.preparing_title');
    $('#hero-sub').textContent = T('mine.preparing_sub');
  } else {
    $('#state-badge').textContent = mining ? T('mine.participating') : T('mine.stopped');
    $('#state-badge').className = 'badge ' + (mining ? 'on' : 'off');
    $('#hero-title').textContent = mining ? T('mine.on_title') : T('mine.ready_title');
    $('#hero-sub').textContent = mining ? T('mine.on_sub') : T('mine.ready_sub');
  }
  $('#toggle').textContent = mining ? T('mine.stop') : T('mine.start');
  $('#toggle').className = 'btn giant ' + (mining ? 'mineral' : 'primary');
  $('#m-blocks').textContent = window.I18N.fmtNum(s.accepted || 0);
  $('#m-speed').innerHTML = fmtHashrate(mining ? (s.hashrate || 0) : 0);
  const pct = (s.cores > 0) ? Math.round((s.threads / s.cores) * 100) : 0;
  $('#m-cpu').textContent = (mining ? pct : 0) + '%';
  $('#m-session').innerHTML = fmtDuration(s.secondsMining || 0);
  $('#m-total').innerHTML = fmtDuration(s.totalSeconds || 0);
  // Work that arrived late (stale): shown only when there is some, with the "this is normal" note.
  const stale = s.stale || 0;
  $('#stale-line').hidden = !(stale > 0);
  if (stale > 0) $('#m-stale').textContent = window.I18N.fmtNum(stale);
  // Real core count -> power label ("50% · 16 of 32 cores").
  if (s.cores && s.cores !== POW_CORES) { POW_CORES = s.cores; refreshPowLabel(); }
}
$('#toggle').addEventListener('click', async () => {
  if (mining) await window.brisvia.stop();
  else await window.brisvia.start(currentIntensity());
  refreshMine();
});
// Mining power: a percentage (1..100) of the machine's cores. Named shortcuts + a slider for fine control.
// Maps legacy named settings (suave/equilibrado/intenso) to a percentage for backward compatibility.
function pctOf(v) { return ({ suave: '25', equilibrado: '50', intenso: '100' })[v] || String(parseInt(v, 10) || 50); }
function currentIntensity() { return String($('#pow-range')?.value || '50'); }
let POW_CORES = 0; // real core count, filled from miner_status
let suppressPreparingUntil = 0; // after a live power change, keep showing "Mining" instead of "Preparing…" for a few seconds
function powThreads(pct) { return POW_CORES > 0 ? Math.max(1, Math.ceil((POW_CORES * pct) / 100)) : 0; }
function refreshPowLabel() {
  const lbl = $('#pow-val'); if (!lbl) return;
  const pct = parseInt($('#pow-range')?.value || '50', 10);
  lbl.textContent = POW_CORES > 0 ? pct + '% · ' + T('mine.cores_of', { n: powThreads(pct), t: POW_CORES }) : pct + '%';
}
// Which named preset the slider value maps to (Light/Balanced/High/Max), by nearest range.
function nearestPreset(pct) { return pct <= 37 ? 25 : pct <= 62 ? 50 : pct <= 87 ? 75 : 100; }
function setPower(pct, apply) {
  pct = Math.max(1, Math.min(100, parseInt(pct, 10) || 50));
  const r = $('#pow-range'); if (r) r.value = pct;
  refreshPowLabel();
  // Auto-select the nearest named preset in BOTH controls (Mine and Settings) so they stay in sync.
  const np = nearestPreset(pct);
  $$('.mine-grid .seg-btn, #set-intensity .seg-btn').forEach((x) => x.classList.toggle('active', parseInt(x.dataset.pct, 10) === np));
  if (apply) {
    window.brisvia.setIntensity(String(pct)); // applies live (backend relaunches the engine)
    window.brisvia.settings.set('defaultIntensity', String(pct)); // remember as the default too
    if (mining) suppressPreparingUntil = Date.now() + 6000; // hide the brief "Preparing…" flash during the relaunch
  }
}
$$('.mine-grid .seg-btn').forEach((b) => b.addEventListener('click', () => setPower(b.dataset.pct, true)));
{
  const r = $('#pow-range');
  if (r) {
    r.addEventListener('input', () => setPower(r.value, false)); // update label while dragging, no relaunch
    r.addEventListener('change', () => setPower(r.value, true));  // apply once when released
  }
}

// ===================== Billetera =====================
function catLabel(cat) {
  if (cat === 'generate' || cat === 'immature') return T('wallet.mined');
  if (cat === 'send') return T('wallet.sent');
  return T('wallet.received');
}
async function loadWallet() {
  const w = await window.brisvia.wallet.summary();
  // Big number = what can be spent now (available). Maturing (mining rewards) and Incoming (unconfirmed) are
  // shown apart, each only if there is an amount. They are NEVER added into the available number.
  $('#bal-amount').textContent = fmt(w.balance);
  const mat = w.immature || 0, inc = w.incoming || 0;
  $('#bd-maturing-row').hidden = !(mat > 0);
  $('#bd-incoming-row').hidden = !(inc > 0);
  if (mat > 0) $('#bd-maturing').textContent = fmt(mat);
  if (inc > 0) $('#bd-incoming').textContent = fmt(inc);
  $('#bal-incoming-wrap').hidden = !(mat > 0 || inc > 0);
  if (!(mat > 0 || inc > 0)) $('#bal-explain').hidden = true;
  const hist = await window.brisvia.wallet.history();
  const list = $('#history-list'), empty = $('#history-empty');
  list.innerHTML = '';
  if (!hist || hist.length === 0) { empty.hidden = false; list.hidden = true; }
  else {
    empty.hidden = true; list.hidden = false;
    hist.forEach((h) => {
      const li = document.createElement('li');
      const inc = h.amount >= 0;
      const label = h.category ? catLabel(h.category) : (inc ? T('wallet.received') : T('wallet.sent'));
      li.innerHTML = `<div><div>${label}</div><div class="muted small">${fmtDate(h.time)}</div></div>
        <div class="hist-amount ${inc ? 'in' : 'out'}">${inc ? '+' : ''}${fmt(h.amount)} BRVA</div>`;
      if (h.txid) li.addEventListener('click', () => openTxDetail(h));
      list.appendChild(li);
    });
  }
}
function fmt(n) { return window.I18N.fmtNum(n, { maximumFractionDigits: 8, useGrouping: false }); }
function fmtDate(epoch) { return window.I18N.fmtDate(epoch); }

// Detalle de un movimiento (click en la lista)
async function openTxDetail(h) {
  $('#txd-rows').innerHTML = `<div class="dr"><span class="muted">${T('common.loading')}</span></div>`;
  openModal('modal-txdetail');
  let d = h;
  try { const full = await window.brisvia.wallet.txDetail(h.txid); if (full) d = { ...h, ...full }; } catch {}
  const inc = (d.amount || 0) >= 0;
  const conf = (d.confirmations != null) ? d.confirmations : 0;
  const confTxt = conf <= 0 ? T('tx.unconfirmed') : T('tx.confirmations', { n: conf, count: conf });
  const label = h.category ? catLabel(h.category) : (inc ? T('wallet.received') : T('wallet.sent'));
  $('#txd-rows').innerHTML =
    `<div class="dr"><span class="muted">${T('tx.type')}</span><span class="val">${label}</span></div>
     <div class="dr"><span class="muted">${T('tx.amount')}</span><span class="val ${inc ? 'pos' : 'neg'}">${inc ? '+' : ''}${fmt(d.amount)} BRVA</span></div>
     <div class="dr"><span class="muted">${T('tx.status')}</span><span class="val">${confTxt}</span></div>
     ${d.blockheight ? `<div class="dr"><span class="muted">${T('tx.block')}</span><span class="val">${d.blockheight}</span></div>` : ''}
     <div class="dr"><span class="muted">${T('tx.date')}</span><span class="val">${fmtDate(d.time) || '—'}</span></div>
     <div class="dr"><span class="muted">${T('tx.txid')}</span></div>
     <div class="copy-line"><code class="mono">${d.txid || '—'}</code><button class="copy-btn" id="txd-copy">${T('common.copy')}</button></div>`;
  const cp = $('#txd-copy');
  if (cp) cp.addEventListener('click', async () => { try { await navigator.clipboard.writeText(d.txid); cp.textContent = T('common.copied'); } catch {} });
}

// Balance chips (Maturing / Incoming): when tapped, they explain why that part cannot be used yet.
$$('.bal-chip').forEach((c) => c.addEventListener('click', () => {
  const ex = $('#bal-explain');
  const key = c.classList.contains('mat') ? 'wallet.maturing_note' : 'wallet.incoming_note';
  if (!ex.hidden && ex.dataset.k === key) { ex.hidden = true; return; }
  ex.textContent = T(key); ex.dataset.k = key; ex.hidden = false;
}));

// Recibir
$('#act-receive').addEventListener('click', async () => {
  const w = await window.brisvia.wallet.summary();
  showReceive(w.address);
});
$('#recv-new').addEventListener('click', async () => { const r = await window.brisvia.wallet.newAddress(); showReceive(r.address); });
$('#recv-copy').addEventListener('click', async () => {
  const addr = $('#recv-addr').textContent;
  try { await navigator.clipboard.writeText(addr); $('#recv-copy').textContent = T('receive.copied_addr'); setTimeout(() => ($('#recv-copy').textContent = T('receive.copy_addr')), 1500); } catch {}
});
// History of generated addresses (oldest first, numbered).
$('#recv-history-toggle').addEventListener('click', async () => {
  const ol = $('#recv-history');
  if (!ol.hidden) { ol.hidden = true; return; }
  const list = (await window.brisvia.wallet.addresses()) || [];
  ol.innerHTML = '';
  list.forEach((a) => { const li = document.createElement('li'); li.innerHTML = `<code class="mono">${a}</code>`; ol.appendChild(li); });
  ol.hidden = false;
});
function showReceive(addr) {
  $('#recv-history').hidden = true;
  $('#recv-addr').textContent = addr || '';
  $('#qr').innerHTML = fakeQR(addr || '');
  openModal('modal-receive');
}
// Deterministic decorative QR (visual placeholder until the real backend generates the actual QR).
function fakeQR(seedStr) {
  const N = 21; let h = 2166136261;
  for (let i = 0; i < seedStr.length; i++) { h ^= seedStr.charCodeAt(i); h = Math.imul(h, 16777619); }
  let rects = '';
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    h ^= h << 13; h ^= h >>> 17; h ^= h << 5; h >>>= 0;
    const corner = (x < 7 && y < 7) || (x >= N - 7 && y < 7) || (x < 7 && y >= N - 7);
    const on = corner ? ((x % 6 === 0 || y % 6 === 0) || (x > 1 && x < 5 && y > 1 && y < 5) || (x >= N-6 && x <= N-2 && y > 1 && y < 5 && (x===N-6||x===N-2||y===2||y===4)) ) : (h % 100) < 46;
    if (on) rects += `<rect x="${x}" y="${y}" width="1" height="1"/>`;
  }
  return `<svg viewBox="0 0 ${N} ${N}" fill="#0B1117" shape-rendering="crispEdges">${rects}</svg>`;
}

// Enviar
$('#act-send').addEventListener('click', () => { $('#send-addr').value = ''; $('#send-amount').value = ''; $('#send-msg').hidden = true; openModal('modal-send'); });
$('#send-go').addEventListener('click', async () => {
  const addr = $('#send-addr').value.trim();
  const amount = parseFloat($('#send-amount').value);
  const msg = $('#send-msg'); msg.hidden = false; msg.className = 'verify-msg err';
  if (!addr || addr.length < 14 || !addr.toLowerCase().includes('brv')) { msg.textContent = T('send.invalid_addr'); return; }
  if (!(amount > 0)) { msg.textContent = T('send.invalid_amount'); return; }
  const r = await window.brisvia.wallet.send(addr, amount);
  if (r && r.ok) { msg.className = 'verify-msg ok'; msg.textContent = T('send.done'); setTimeout(() => closeModal('modal-send'), 1200); loadWallet(); }
  else { msg.textContent = r && r.error ? transError(r.error) : T('send.fail'); }
});

// ===================== Ajustes =====================
async function loadSettings() {
  const s = await window.brisvia.settings.get();
  $('#set-autostart').checked = !!s.autostart;
  $('#set-tray').checked = s.tray !== false;
  setPower(parseInt(pctOf(s.defaultIntensity), 10), false); // sync both power controls with the saved default
  $$('#set-language .seg-btn').forEach((b) => b.classList.toggle('active', b.dataset.lang === window.I18N.lang));
}
$('#set-autostart').addEventListener('change', (e) => window.brisvia.settings.set('autostart', e.target.checked));
$('#set-tray').addEventListener('change', (e) => window.brisvia.settings.set('tray', e.target.checked));
$$('#set-intensity .seg-btn').forEach((b) => b.addEventListener('click', () => setPower(parseInt(b.dataset.pct, 10), true)));
// Selector de idioma
$$('#set-language .seg-btn').forEach((b) => b.addEventListener('click', () => {
  window.I18N.setLang(b.dataset.lang);
  if (window.brisvia.setLanguage) window.brisvia.setLanguage(b.dataset.lang); // rebuilds the tray menu
}));
$$('.social').forEach((b) => b.addEventListener('click', () => window.brisvia.openUrl(b.dataset.url)));

// Seguridad y respaldo
$('#set-security').addEventListener('click', () => openModal('modal-security'));

// ===================== Actualizaciones (auto-actualizador) =====================
// On startup (and every 6h) it checks for a new signed version; if there is one, it shows a pop-up with a button
// that downloads it, verifies its signature, installs and restarts. It can also be checked manually from Settings.
let updatePendingVersion = null;
async function checkForUpdate(manual) {
  const btn = $('#set-update');
  if (manual && btn) { btn.disabled = true; btn.textContent = T('update.checking'); }
  let res = null;
  try { res = window.brisvia.checkUpdate ? await window.brisvia.checkUpdate() : null; } catch {}
  if (res && res.available) {
    updatePendingVersion = res.version;
    let dismissed = null; try { dismissed = localStorage.getItem('brv_update_dismissed'); } catch {}
    // On the automatic check, don't nag again if the user already chose "Later" for THIS version.
    if (!manual && dismissed === res.version) { if (btn) { btn.disabled = false; btn.textContent = T('update.check'); } return; }
    openModal('modal-update'); // pop-up: OK installs, Later dismisses
    if (btn) { btn.disabled = false; btn.textContent = T('update.check'); }
  } else if (manual && btn) {
    btn.disabled = false;
    btn.textContent = res ? T('update.none') : T('update.error');
    setTimeout(() => { btn.textContent = T('update.check'); }, 4000);
  }
}
async function installUpdate() {
  const b = $('#upd-ok');
  if (b) { b.disabled = true; b.textContent = T('update.installing'); }
  try { await window.brisvia.installUpdate(); } // downloads, verifies the signature, installs and restarts
  catch { if (b) { b.disabled = false; b.textContent = T('update.install_now'); } }
}
if ($('#set-update')) $('#set-update').addEventListener('click', () => checkForUpdate(true));
if ($('#upd-ok')) $('#upd-ok').addEventListener('click', installUpdate);
if ($('#upd-later')) $('#upd-later').addEventListener('click', () => {
  try { if (updatePendingVersion) localStorage.setItem('brv_update_dismissed', updatePendingVersion); } catch {}
  closeModal('modal-update');
});

// See the 12 words: they are requested from the backend on the spot; they are not saved in any file.
$('#sec-view').addEventListener('click', async () => {
  const words = await window.brisvia.wallet.getSeed();
  const grid = $('#seed-grid-view'); grid.innerHTML = '';
  (words || []).forEach((w) => { const li = document.createElement('li'); li.textContent = w; grid.appendChild(li); });
  closeModal('modal-security'); openModal('modal-seed');
});
// Verificar respaldo: el usuario escribe sus 12 palabras y se comparan con las de la billetera.
$('#sec-verify').addEventListener('click', () => {
  const grid = $('#vb-grid'); grid.innerHTML = '';
  for (let i = 0; i < 12; i++) {
    const li = document.createElement('li');
    const inp = document.createElement('input');
    inp.type = 'text'; inp.autocomplete = 'off'; inp.spellcheck = false; inp.setAttribute('aria-label', `${i + 1}`);
    li.appendChild(inp); grid.appendChild(li);
  }
  $('#vb-msg').hidden = true;
  closeModal('modal-security'); openModal('modal-verify-backup');
});
$('#vb-check').addEventListener('click', async () => {
  const words = [...$('#vb-grid').querySelectorAll('input')].map((i) => i.value.trim().toLowerCase()).filter(Boolean);
  const msg = $('#vb-msg'); msg.hidden = false;
  if (words.length !== 12) { msg.className = 'verify-msg err'; msg.textContent = T('security.verify_len', { n: words.length }); return; }
  const real = await window.brisvia.wallet.getSeed();
  const ok = Array.isArray(real) && real.length === 12 && real.every((w, i) => w === words[i]);
  msg.className = ok ? 'verify-msg ok' : 'verify-msg err';
  msg.textContent = ok ? T('security.verify_ok') : T('security.verify_bad');
});

// ===================== Modales =====================
function openModal(id) { $('#' + id).hidden = false; }
function closeModal(id) { $('#' + id).hidden = true; }
$$('[data-close]').forEach((b) => b.addEventListener('click', (e) => { const ov = e.target.closest('.overlay'); if (ov) ov.hidden = true; }));
$$('.overlay').forEach((ov) => ov.addEventListener('click', (e) => { if (e.target === ov && ov.id !== 'setup') ov.hidden = true; }));

// ===================== Estado de red (modo nodo real) =====================
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
function setNet(connected, key) {
  const dot = document.querySelector('.net-dot');
  // The "live" class turns on the connected color and the pulse animation (both defined in CSS).
  if (dot) dot.classList.toggle('live', connected);
  const lbl = $('#net-label');
  if (lbl) lbl.textContent = T(key);
}
let syncing = false, syncProgress = 0;
async function pollNet() {
  if (!window.brisvia.isReal) return;
  const info = await window.brisvia.nodeInfo();
  const st = await window.brisvia.nodeStatus();
  const connected = !!(info && info.connected);
  const walletReady = !!(st && st.walletReady);
  // Syncing = connected but still catching up with the shared chain (do not mine yet).
  syncing = connected && !!(info && info.ibd);
  syncProgress = (info && info.verificationprogress != null) ? Number(info.verificationprogress) : 0;
  const netKey = !connected ? 'net.connecting' : (syncing ? 'net.syncing' : (walletReady ? 'net.connected' : 'net.preparing'));
  setNet(connected && !syncing, netKey);
  if ($('#nr-status')) {
    $('#nr-status').textContent = !connected ? T('net_panel.connecting') : (syncing ? T('net.syncing') : (walletReady ? T('net_panel.connected') : T('net_panel.preparing')));
    $('#nr-height').textContent = connected ? window.I18N.fmtNum(info.blocks ?? 0) : '—';
    $('#nr-peers').textContent = connected ? (info.peers ?? 0) : '—';
    $('#nr-diff').textContent = (connected && info.difficulty != null) ? window.I18N.fmtNum(info.difficulty, { maximumFractionDigits: 2 }) : '—';
  }
}

// On language change: re-apply static texts (i18n handles that) + re-render the dynamic ones.
document.addEventListener('langchange', () => {
  renderOnb();
  refreshMine();
  refreshPowLabel();
  updateTestnetBanner();
  const wv = document.querySelector('.view[data-view="wallet"]');
  if (wv && !wv.hidden) loadWallet();
  // Re-translate the balance explanation if it's open (it's set on click, so it wouldn't refresh otherwise).
  const ex = $('#bal-explain');
  if (ex && !ex.hidden && ex.dataset.k) ex.textContent = T(ex.dataset.k);
  $$('#set-language .seg-btn').forEach((b) => b.classList.toggle('active', b.dataset.lang === window.I18N.lang));
});

// ===================== Tooltips (explicaciones al pasar el mouse) =====================
// Cualquier elemento con data-tip-key="X" muestra el texto tips.X a los ~0,5s de dejar el mouse encima.
// Explains in plain words terms a non-technical user may not know (Blocks, Difficulty, etc.).
(function initTooltips() {
  let el = null, timer = null;
  function box() {
    if (!el) { el = document.createElement('div'); el.className = 'tooltip'; document.body.appendChild(el); }
    return el;
  }
  function show(target) {
    const key = target.getAttribute('data-tip-key');
    if (!key) return;
    const txt = T('tips.' + key);
    if (!txt || txt.charAt(0) === '[') return; // no translation available: skip
    const b = box();
    b.textContent = txt;
    b.classList.add('on');
    const r = target.getBoundingClientRect();
    let left = r.left;
    if (left + b.offsetWidth > window.innerWidth - 8) left = window.innerWidth - 8 - b.offsetWidth;
    if (left < 8) left = 8;
    let top = r.bottom + 8;
    if (top + b.offsetHeight > window.innerHeight - 8) top = r.top - b.offsetHeight - 8;
    b.style.left = left + 'px';
    b.style.top = top + 'px';
  }
  function hide() { if (timer) { clearTimeout(timer); timer = null; } if (el) el.classList.remove('on'); }
  document.addEventListener('mouseover', (e) => {
    const t = e.target.closest('[data-tip-key]');
    if (!t) return;
    hide();
    timer = setTimeout(() => show(t), 500);
  });
  document.addEventListener('mouseout', (e) => { if (e.target.closest('[data-tip-key]')) hide(); });
  document.addEventListener('click', hide);
})();

// ===================== Red de prueba (testnet): aviso + cuenta regresiva al minado real =====================
// Real mining start (mainnet). Fixed in code so the whole "test network" notice — including this
// countdown — hides ITSELF the moment real mining begins, with no update required.
const MAINNET_START = Date.UTC(2026, 7, 1, 15, 0, 0); // Sat Aug 1 2026, 15:00 UTC
function updateTestnetBanner() {
  const banner = $('#testnet-banner');
  if (!banner) return;
  const diff = MAINNET_START - Date.now();
  if (diff <= 0) { banner.hidden = true; return; } // real mining already started: the notice disappears by itself
  banner.hidden = false;
  const cd = $('#tb-countdown');
  if (!cd) return;
  const days = Math.floor(diff / 86400000);
  const hours = Math.floor((diff % 86400000) / 3600000);
  cd.hidden = false;
  cd.textContent = days >= 1 ? T('testnet.mainnet_in', { d: days, h: hours }) : T('testnet.mainnet_soon');
}
setInterval(updateTestnetBanner, 60000); // refresca el contador cada minuto

// ===================== Arranque =====================
async function init() {
  // Idioma: el guardado; o el del SO la primera vez (systemLocale del backend real; navigator.language en preview).
  let lang = null;
  try { lang = localStorage.getItem('brv_lang'); } catch {}
  if (!lang) {
    let sysLoc = 'en';
    try { sysLoc = (window.brisvia.systemLocale ? await window.brisvia.systemLocale() : navigator.language) || 'en'; } catch {}
    lang = String(sysLoc).toLowerCase().startsWith('es') ? 'es' : 'en';
  }
  window.I18N.setLang(lang);
  if (window.brisvia.setLanguage) window.brisvia.setLanguage(lang);
  updateTestnetBanner();
  // Auto-check for updates on startup (non-blocking): if there is a new version, the notice appears.
  setTimeout(() => { checkForUpdate(false); }, 3000);
  // Also check periodically so someone who leaves the app open for days still gets the update pop-up on its own.
  setInterval(() => { checkForUpdate(false); }, 6 * 60 * 60 * 1000); // every 6 hours

  if (window.brisvia.isReal) {
    $('#setup').hidden = true;
    setNet(false, 'net.connecting');
    let ready = false, decided = false;
    for (let i = 0; i < 150 && !decided; i++) {
      await pollNet();
      const s = await window.brisvia.nodeStatus();
      if (s && s.connected) {
        if (s.walletReady) { ready = true; decided = true; }
        else if (s.walletOnDisk === false) { decided = true; }
      }
      if (!decided) await sleep(1000);
    }
    if (ready) {
      $('#setup').hidden = true;
      showView('wallet');
      loadWallet();
    } else {
      $('#setup').hidden = false;
      onbStep = 0; renderOnb(); setupStep('welcome');
    }
    setInterval(pollNet, 3000);
  } else {
    const exists = await window.brisvia.wallet.exists();
    if (exists && localStorage.getItem('brisvia_onboarded') === '1') {
      $('#setup').hidden = true;
      showView('wallet');
    } else {
      $('#setup').hidden = false;
      onbStep = 0; renderOnb(); setupStep('welcome');
    }
  }
  refreshMine();
  setInterval(refreshMine, 1000);
  setInterval(() => {
    const wv = document.querySelector('.view[data-view="wallet"]');
    if (window.brisvia.isReal && wv && !wv.hidden) loadWallet();
  }, 4000);
}
init();
